FROM python:3.10.6-slim-buster
LABEL maintainer="chichi13"

# Keeping the image up to date
RUN apt-get update -y && apt-get upgrade -y && \
    rm -rf /var/lib/apt/lists/* && \
    pip install --upgrade pip && useradd -ms /bin/bash app

USER app
WORKDIR /app

ENV PATH="/home/app/.local/bin:${PATH}"

# Copy only requirements/ for caching purpose
COPY --chown=app:app requirements/ requirements/

RUN pip install --user --no-cache-dir -r requirements/prod.txt

COPY --chown=app:app . /app

CMD [ "python3", "main.py"]